name: Publish your flake.
branding:
  icon: "box"
  color: "purple"
description: "Publish your flake."

inputs:
  visibility:
    description: "`public` or `unlisted`"
    required: true
  upload-name:
    description: The name of your published flake. In the format of OrgName/RepoName. OrgName must match your organization's GitHub root name or the publish will fail.
    required: true
    default: null
  repository:
    description: The actual GitHub repository containing your flake. In the format of OrgName/RepoName.
    required: true
    default: ${{ github.repository }}
  mirror:
    description: If the repository is mirrored via DeterminateSystems' mirror functionality. This is only usable by DeterminateSystems.
    required: false
    default: false
  directory:
    description: the directory of your flake (useful for subflakes)
    required: false
    default: null
  git-root:
    description: the git root of your flake
    required: false
    default: .
  tag:
    description: "example: v0.1.1"
    required: false
    default: null
  rolling-prefix:
    description: "For untagged releases, set a rolling prefix to be suffixed with the commit count. ie: v0.1 will be suffixed with .123 producing a release named v0.1.123-revision"
    required: false
    default: null
  host:
    description: "The flakehub server to use"
    required: false
    default: "https://api.flakehub.com"
  log-directives:
    description: A list of Tracing directives, comma separated, `-`s replaced with `_` (eg. `nix_installer=trace`, see https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives)
    required: false
    default: "flakehub_push=info"
  logger:
    description: The logger to use for install (eg. `pretty`, `json`, `full`, `compact`)
    required: false
    default: "full"
  github-token:
    description: A GitHub token for making authenticated GitHub API requests
    default: ${{ github.token }}
  extra-tags:
    description: |
      Extra user-supplied tags for the flake as a comma-separated string. These tags are added to the topics associated with the flake's GitHub repo. Only alphanumeric characters and hyphens are allowed in tags.

      You can add up to five extra tags; tags beyond the first five will be ignored.
    required: false
    default: ""
  flakehub-push-binary:
    description: Run a version of the `flakehub-push` binary from somewhere already on disk. Conflicts with all other `flakehub-push-*` options.
  flakehub-push-branch:
    description: The branch of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
    default: main
  flakehub-push-pr:
    description: The PR of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-revision:
    description: The revision of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-tag:
    description: The tag of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-url:
    description: A URL pointing to a `flakehub-push` binary. Overrides all other `flakehub-push-*` options.
    required: false

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions
runs:
  using: composite
  steps:
  - name: Install `flakehub-push`
    shell: bash
    env:
      FLAKEHUB_PUSH_VISIBLITY: ${{ inputs.visibility }}
      FLAKEHUB_PUSH_TAG: ${{ inputs.tag }}
      FLAKEHUB_PUSH_ROLLING_PREFIX: ${{ inputs.rolling-prefix }}
      FLAKEHUB_PUSH_HOST: ${{ inputs.host }}
      FLAKEHUB_PUSH_LOG_DIRECTIVES: ${{ inputs.log-directives }}
      FLAKEHUB_PUSH_LOGGER: ${{ inputs.logger }}
      FLAKEHUB_PUSH_GITHUB_TOKEN: ${{ inputs.github-token }}
      FLAKEHUB_PUSH_UPLOAD_NAME: ${{ inputs.upload-name }}
      FLAKEHUB_PUSH_MIRROR: ${{ inputs.mirror }}
      FLAKEHUB_PUSH_REPOSITORY: ${{ inputs.repository }}
      FLAKEHUB_PUSH_DIRECTORY: ${{ inputs.directory }}
      FLAKEHUB_PUSH_GIT_ROOT: ${{ inputs.git-root }}
      FLAKEHUB_PUSH_EXTRA_TAGS: ${{ inputs.extra-tags }}
      # Also GITHUB_REPOSITORY, GITHUB_REF_NAME, GITHUB_TOKEN, ACTIONS_ID_TOKEN_REQUEST_TOKEN, ACTIONS_ID_TOKEN_REQUEST_URL
    run: |
      if [ "${RUNNER_OS}" == "Linux" ]; then
        export ARCHITECTURE_OS="Linux"
      else
        echo "${RUNNER_OS} not supported"
        exit 1
      fi

      if [ "${RUNNER_ARCH}" == "X64" ]; then
        export ARCHITECTURE_ARCH="X64"
      else
        echo "${RUNNER_ARCH} not supported"
        exit 1
      fi

      export ARCHITECTURE="${ARCHITECTURE_ARCH}-${ARCHITECTURE_OS}"

      if [ -n "${{ inputs.flakehub-push-url }}" ]; then
        export FLAKEHUB_PUSH_URL="${{ inputs.flakehub-push-url }}"
      else
        if [ -n "${{ inputs.flakehub-push-pr }}" ]; then
          export FLAKEHUB_PUSH_URL="https://install.determinate.systems/flakehub-push/pr/${{ inputs.flakehub-push-pr }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.flakehub-push-tag }}" ]; then
          export FLAKEHUB_PUSH_URL="https://install.determinate.systems/flakehub-push/tag/${{ inputs.flakehub-push-tag }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.flakehub-push-revision }}" ]; then
          export FLAKEHUB_PUSH_URL="https://install.determinate.systems/flakehub-push/rev/${{ inputs.flakehub-push-revision }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.flakehub-push-branch }}" ]; then
          export FLAKEHUB_PUSH_URL="https://install.determinate.systems/flakehub-push/branch/${{ inputs.flakehub-push-branch }}/${ARCHITECTURE}?ci=github"
        else
          export FLAKEHUB_PUSH_URL="https://install.determinate.systems/flakehub-push/stable/${ARCHITECTURE}?ci=github"
        fi
      fi
      echo "Set FLAKEHUB_PUSH_URL=$FLAKEHUB_PUSH_URL"

      if [ -n "${{ inputs.flakehub-push-binary }}" ]; then
        chmod +x ${{ inputs.flakehub-push-binary }}
        exec ${{ inputs.flakehub-push-binary }}
      else
        DEST=$(mktemp -d)
        curl --retry 20 -L $FLAKEHUB_PUSH_URL -o $DEST/flakehub-push
        chmod +x $DEST/flakehub-push
        exec $DEST/flakehub-push
      fi
