name: Publish Nix flakes to FlakeHub
branding:
  icon: "box"
  color: "purple"
description: "Find, install, and publish Nix Flakes with FlakeHub."

inputs:
  visibility:
    description: "`public`, `unlisted`, or `private` (private flakes are available only on a [FlakeHub paid plan](https://flakehub.com/signup))"
    required: true
  name:
    description: The name of your published flake. In the format of OrgName/RepoName. OrgName must match your organization's GitHub root name or the publish will fail.
    required: false
    default: null
  repository:
    description: The actual GitHub repository containing your flake. In the format of OrgName/RepoName.
    required: true
    default: ${{ github.repository }}
  mirror:
    description: If the repository is mirrored via DeterminateSystems' mirror functionality. This is only usable by DeterminateSystems.
    required: false
    default: false
  directory:
    description: The path of your flake relative to the root of the repository. Useful for subflakes.
    required: false
    default: null
  git-root:
    description: The root directory of your Git repository.
    required: false
    default: .
  tag:
    description: The Git tag to use, for non-rolling releases. This must be the character `v` followed by a SemVer version, e.g. `v0.1.1`.
    required: false
    default: null
  rev:
    description: The Git revision SHA to use for non-rolling releases.
    required: false
    default: null
  rolling-minor:
    description: "Specify the SemVer minor version of your rolling releases. All releases will follow the versioning scheme '0.[rolling-minor].[commit count]+rev-[git sha]'"
    required: false
    default: null
  rolling:
    description: |
      For untagged releases, use a rolling versioning scheme.

      When this is enabled, the default versioning scheme is 0.1.[commit count]+rev-[git sha]. To customize the SemVer minor version, set the `rolling-minor` option.
    required: false
    default: false
  host:
    description: "The FlakeHub server to use."
    required: false
    default: "https://api.flakehub.com"
  log-directives:
    description: A comma-separated list of [tracing directives](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives). `-`s are replaced with `_`s (such as `nix_installer=trace`).
    required: false
    default: "flakehub_push=info"
  logger:
    description: The logger to use. Options are `pretty`, `json`, `full` and `compact`.
    required: false
    default: "full"
  github-token:
    description: A GitHub token for making authenticated GitHub API requests.
    default: ${{ github.token }}
  extra-tags:
    description: "DEPRECATED: Please use `extra-labels` instead."
    required: false
    default: ""
  extra-labels:
    description: |
      `flakehub-push` automatically uses the GitHub repo's topics as labels. This `extra-labels` parameter enables you to add extra labels beyond that as a comma-separated string. Only alphanumeric characters and hyphens are allowed in labels and the maximum length of labels is 50 characters. You can specify a maximum of 20 extra labels, and have a maximum of 25 labels, including those that we retrieve from GitHub. Any labels after the 25th will be ignored.
    required: false
    default: ""
  spdx-expression:
    description: A valid SPDX license expression. This will be used in place of what GitHub claims your repository's `spdxIdentifier` is.
    required: false
    default: ""
  error-on-conflict:
    description: Whether to error if a release for the same version has already been uploaded.
    required: false
    default: false
  include-output-paths:
    description: Whether to register the output paths of each flake output with FlakeHub.
    required: false
    default: false

  my-flake-is-too-big:
    description: Please read the source code of flakehub-push before using this.
    required: false
    default: false

  # Used to construct the binary download URL
  source-binary:
    description: Run a version of the `flakehub-push` binary from somewhere already on disk. Conflicts with all `source-*` options.
    required: false
  source-branch:
    description: The branch of `flakehub-push` to use. Conflicts with all other `source-*` options.
    required: false
    default: main
  source-pr:
    description: The pull request (PR) of `flakehub-push` to use. Conflicts with all other `source-*` options.
    required: false
  source-revision:
    description: The revision of `flakehub-push` to use. Conflicts with all other `source-*` options.
    required: false
  source-tag:
    description: The tag of `flakehub-push` to use. Conflicts with all other `source-*` options.
    required: false
  source-url:
    description: A URL pointing to a `flakehub-push` binary. Overrides all other `source-*` options.
    required: false
  _internal-strict-mode:
    description: Whether to fail when any errors are thrown. Used only to test the Action; do not set this in your own workflows.
    default: false

  # DEPRECATED options (use the `source-*` equivalents above)
  flakehub-push-binary:
    description: Run a version of the `flakehub-push` binary from somewhere already on disk. Conflicts with all `flakehub-push-*` options.
    required: false
  flakehub-push-branch:
    description: The branch of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-pr:
    description: The pull request (PR) of `flakehub-push` to use. Conflicts with all `flakehub-push-*` options.
    required: false
  flakehub-push-revision:
    description: The revision of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-tag:
    description: The tag of `flakehub-push` to use. Conflicts with all other `flakehub-push-*` options.
    required: false
  flakehub-push-url:
    description: A URL pointing to a `flakehub-push` binary. Overrides all other `flakehub-push-*` options.
    required: false

runs:
  using: "node20"
  main: "dist/index.js"
