name: Publish your flake.
branding:
  icon: "box"
  color: "purple"
description: "Publish your flake."

inputs:
  visibility:
    description: "`public` or `hidden`"
    required: true
  directory:
    description: where in the repository is your flake.nix, root is strongly recommended
    required: true
    default: .
  name:
    description: the name of your published flake, strongly recommended to leave this unchanged. In the format of OrgName/RepoName. OrgName must match your organization's GitHub root name or the publish will fail.
    required: true
    default: null
  mirrored-for:
    description: "example: NixOS/nix"
    required: false
    default: null
  tag:
    description: "example: v0.1.1"
    required: false
    default: null
  rolling-prefix:
    description: "For untagged releases, set a rolling prefix to be suffixed with the commit count. ie: v0.1 will be suffixed with .123 producing a release named v0.1.123-revision"
    required: false
    default: null
  host:
    description: "The nxfr server to use"
    required: false
    default: "https://nxfr.fly.dev"
  log-directives:
    description: A list of Tracing directives, comma separated, `-`s replaced with `_` (eg. `nix_installer=trace`, see https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives)
    required: false
    default: "nxfr_push=info"
  logger:
    description: The logger to use for install (eg. `pretty`, `json`, `full`, `compact`)
    required: false
    default: "full"
  github-token:
    description: A GitHub token for making authenticated GitHub API requests
    default: ${{ github.token }}
  nxfr-push-binary:
    description: Run a version of the `nxfr-push` binary from somewhere already on disk. Conflicts with all other `nxfr-push-*` options.
  nxfr-push-branch:
    description: The branch of `nxfr-push` to use. Conflicts with all other `nxfr-push-*` options.
    required: false
    default: main
  nxfr-push-pr:
    description: The PR of `nxfr-push` to use. Conflicts with all other `nxfr-push-*` options.
    required: false
  nxfr-push-revision:
    description: The revision of `nix-nxfr-push` to use. Conflicts with all other `nxfr-push-*` options.
    required: false
  nxfr-push-tag:
    description: The tag of `nxfr-push` to use. Conflicts with all other `nxfr-push-*` options.
    required: false
  nxfr-push-url:
    description: A URL pointing to a `nxfr-push` binary. Overrides all other `nxfr-push-*` options.
    required: false

# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-docker-container-actions
runs:
  using: composite
  steps:
  - name: Install `nxfr-push`
    shell: bash
    env:
      NXFR_PUSH_DIRECTORY: ${{ inputs.directory }}
      NXFR_PUSH_VISIBLITY: ${{ inputs.visibility }}
      NXFR_PUSH_MIRRORED_FOR: ${{ inputs.mirrored-for }}
      NXFR_PUSH_TAG: ${{ inputs.tag }}
      NXFR_PUSH_ROLLING_PREFIX: ${{ inputs.rolling-prefix }}
      NXFR_PUSH_HOST: ${{ inputs.host }}
      NXFR_PUSH_LOG_DIRECTIVES: ${{ inputs.log-directives }}
      NXFR_PUSH_LOGGER: ${{ inputs.logger }}
      NXFR_PUSH_GITHUB_TOKEN: ${{ inputs.github-token }}
      # Also GITHUB_REPOSITORY, GITHUB_REF_NAME, GITHUB_TOKEN, ACTIONS_ID_TOKEN_REQUEST_TOKEN, ACTIONS_ID_TOKEN_REQUEST_URL
    run: |
      if [ "${RUNNER_OS}" == "Linux" ]; then
        export ARCHITECTURE_OS="linux"
      elif [ "${RUNNER_OS}" == "macOS" ]; then
        export ARCHITECTURE_OS="darwin"
      else
        echo "${RUNNER_OS} not supported"
        exit 1
      fi

      if [ "${RUNNER_ARCH}" == "X64" ]; then
        export ARCHITECTURE_ARCH="x86_64"
      elif [ "${RUNNER_ARCH}" == "ARM64" ]; then
        export ARCHITECTURE_ARCH="aarch64"
      else
        echo "${RUNNER_ARCH} not supported"
        exit 1
      fi

      export ARCHITECTURE="${ARCHITECTURE_ARCH}-${ARCHITECTURE_OS}"

      if [ -n "${{ inputs.nxfr-push-url }}" ]; then
        export NXFR_PUSH_URL="${{ inputs.nxfr-push-url }}"
      else
        if [ -n "${{ inputs.nxfr-push-pr }}" ]; then
          export NXFR_PUSH_URL="https://install.determinate.systems/nxfr-push/pr/${{ inputs.nxfr-push-pr }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.nxfr-push-tag }}" ]; then
          export NXFR_PUSH_URL="https://install.determinate.systems/nxfr-push/tag/${{ inputs.nxfr-push-tag }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.nxfr-push-revision }}" ]; then
          export NXFR_PUSH_URL="https://install.determinate.systems/nxfr-push/rev/${{ inputs.nxfr-push-revision }}/${ARCHITECTURE}?ci=github"
        elif [ -n "${{ inputs.nxfr-push-branch }}" ]; then
          export NXFR_PUSH_URL="https://install.determinate.systems/nxfr-push/branch/${{ inputs.nxfr-push-branch }}/${ARCHITECTURE}?ci=github"
        else
          export NXFR_PUSH_URL="https://install.determinate.systems/nxfr-push/stable/${ARCHITECTURE}?ci=github"
        fi
      fi
      echo "Set NXFR_PUSH_URL=$NXFR_PUSH_URL"

      if [ -n "${{ inputs.nxfr-push-binary }}" ]; then
        chmod +x ${{ inputs.nxfr-push-binary }}
        exec ${{ inputs.nxfr-push-binary }}
      else
        DEST=$(mktemp -d)
        curl --retry 20 -L $NXFR_PUSH_URL -o $DEST/nxfr-push
        chmod +x $DEST/nxfr-push
        exec $DEST/nxfr-push
      fi
    
