name: Publish your flake.
branding:
  icon: "box"
  color: "purple"
description: "Publish your flake."

inputs:
  visibility:
    description: "`public` or `hidden`"
    required: true
  directory:
    description: where in the repository is your flake.nix, root is strongly recommended
    required: true
    default: .
  name:
    description: the name of your published flake, strongly recommended to leave this unchanged. In the format of OrgName/RepoName. OrgName must match your organization's GitHub root name or the publish will fail.
    required: true
    default: ""
  mirrored-for:
    description: "example: NixOS/nix"
    required: false
    default: ""
  tag:
    description: "example: v0.1.1"
    required: false
    default: ""
  registry_json:
   description: "if you use a custom nix flake registry json"
   required: false
   default: ""

runs:
  using: composite
  steps:
    - name: Push
      shell: bash
      run: |
        set -eux
        cd "${{ inputs.directory }}"
        cat <<'EOF' > $PWD/registry.json
        ${{ inputs.registry_json }}
        EOF
        $GITHUB_ACTION_PATH/release.sh ${{ inputs.visibility }} "${{ inputs.name }}" "${{ inputs.mirrored-for }}" "${{ inputs.tag }}" "$PWD/registry.json"
