name: TypeScript-based Action

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-dist-up-to-date:
    name: Check the dist/ folder is up to date
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install pnpm dependencies
        run: nix develop --command pnpm install
      - name: Check formatting
        run: nix develop --command pnpm run check-fmt
      - name: Run ESLint
        run: nix develop --command pnpm run lint
      - name: Run tests
        run: nix develop --command pnpm run test
      - name: Build bundle
        run: nix develop --command pnpm run build
      - name: Package as Node.js runnable
        run: nix develop --command pnpm run package
      - name: Check git status
        run: git status --porcelain=v1
      - name: Ensure no staged changes
        run: git diff --exit-code
