name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Nix formatting"
        run: git ls-files '*.nix' | nix develop --command xargs nixpkgs-fmt --check

      - name: "Rust formatting"
        run: nix develop --command cargo fmt --check

      - name: "Clippy"
        run: nix develop --command cargo clippy --all-targets --all-features --  -Dwarnings

  build-artifacts-X64-Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Nix Flake Check"
        run: nix flake check --show-trace --print-build-logs

      - name: Build package
        run: "nix build .# -L --fallback"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: flakehub-push-X64-Linux
          path: result/bin/flakehub-push
          retention-days: 1

  build-artifacts-X64-macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: "Nix Flake Check"
        run: nix flake check --show-trace --print-build-logs

      - name: Build package
        run: "nix build .# -L --fallback"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: flakehub-push-X64-macOS
          path: result/bin/flakehub-push
          retention-days: 1
