name: Production test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  production-test:
    needs: build
    if: |
        (github.event.action == 'labeled' && github.event.label.name == 'production test')
        || (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'production test'))
    runs-on: ubuntu-22.04
    permissions:
      id-token: write # In order to request a JWT for AWS auth
      contents: read # Specifying id-token wiped this out, so manually specify that this action is allowed to checkout this private repo
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: nxfr-push-X64-Linux
          path: nxfr-push-X64-Linux
      
      - name: Production test
        if: |
            (github.event.action == 'labeled' && github.event.label.name == 'production test')
            || (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'production test'))
        uses: ./
        with:
          visibility: "hidden"
          rolling-prefix: "0.0"
          log-directives: "nxfr_push=trace"
          logger: "pretty"
          nxfr-push-binary: ./nxfr-push-X64-Linux/nxfr-push-X64-Linux