name: Release Branch

on:
  push:
    branches:
      # NOTE: make sure any branches here are also valid directory names,
      # otherwise creating the directory and uploading to s3 will fail
      - "main"

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    if: |
      github.event.pull_request.head.repo.full_name == 'DeterminateSystems/nxfr-push'
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'upload to s3')
        || (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'upload to s3'))
      )

  release:
    needs: build

    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          aws-region: us-east-2

      - name: Create the artifacts directory
        run: rm -rf ./artifacts && mkdir ./artifacts

      - uses: actions/download-artifact@v3
        with:
          name: nxfr-push-X64-Linux
          path: nxfr-push-X64-Linux

      - name: Persist the nxfr-push binary
        run: cp ./nxfr-push-X64-Linux/nxfr-push ./artifacts/nxfr-push-X64-Linux

      - name: Publish Release (Branch)
        env:
          AWS_BUCKET: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
        run: |
          .github/workflows/upload_s3.sh branch "${{ github.ref_name }}" "$GITHUB_SHA"
