name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  flake-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: DeterminateSystems/nix-installer-action-cache@main

      - name: "Nix formatting"
        run: git ls-files '*.nix' | nix develop --command xargs nixpkgs-fmt --check

      - name: "Rust formatting"
        run: nix develop --command cargo fmt --check

      - name: "Clippy"
        run: nix develop --command cargo clippy --all-targets --all-features --  -Dwarnings

      - name: "Nix Flake Check"
        run: nix flake check --print-build-logs

      - name: "Build the image"
        run: nix build .#dockerImages.x86_64-linux.default